version: 2.1
orbs:
  # orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
       # install dependencies for front-end application
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
       # install dependencies for back-end application
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
         # build front-end application
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
        # build back-end application
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
        # deploy front-end application
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
        # build back-end application
          name: Deploy backend
          command: |
            npm run backend:deploy

