version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy

Under jobs -> steps, we have added just after checkout a step to set up the AWS CLI aws-cli/setup. This will install and configure the AWS CLI on the CircleCI Server. The other thing we have changed inside the yml file is the addition of the last step for deploying:

      - run:
          name: Deploy front App
          command: |
            npm run frontend:deploy

      - run:
          name: Deploy back App
          command: |
            npm run backend:deploy
